# Generated by Django 5.2 on 2025-04-03 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_mesero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.mesero')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orden_platos', to='restaurante.orden')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.plato')),
            ],
        ),
    ]
